# Generated by Django 6.0.6 on 2026-07-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteAnaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('commentaire', models.TextField()),
                ('action_prevue', models.CharField(choices=[('aucune', 'Aucune'), ('signalisation', 'Signalisation'), ('ralentisseur', 'Ralentisseur'), ('eclairage', 'Éclairage'), ('autre', 'Autre')], default='aucune', max_length=15)),
                ('details_action', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('soumise', 'Soumise'), ('en_cours', 'En cours'), ('realisee', 'Réalisée')], default='soumise', max_length=10)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
