# Generated by Django 6.0.6 on 2026-07-05 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anaser', '0001_initial'),
        ('incidents', '0001_initial'),
        ('zones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alerteanaser',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks_anaser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerteanaser',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_anaser', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='alerteanaser',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_anaser', to='zones.zone'),
        ),
        migrations.AddConstraint(
            model_name='alerteanaser',
            constraint=models.CheckConstraint(condition=models.Q(('zone__isnull', False), ('incident__isnull', False), _connector='OR'), name='alerte_anaser_zone_ou_incident_requis'),
        ),
    ]
