# Generated by Django 6.0.6 on 2026-07-05 01:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boitier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_key_hash', models.CharField(max_length=128)),
                ('proprietaire_nom', models.CharField(blank=True, max_length=150)),
                ('proprietaire_telephone', models.CharField(blank=True, max_length=30)),
                ('numero_immatriculation', models.CharField(blank=True, max_length=30)),
                ('derniere_latitude', models.FloatField(blank=True, null=True)),
                ('derniere_longitude', models.FloatField(blank=True, null=True)),
                ('derniere_localisation_maj', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('maintenance', 'Maintenance')], default='actif', max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_synchronisation', models.DateTimeField(auto_now_add=True)),
                ('nombre_incidents_synchronises', models.PositiveIntegerField(default=0)),
                ('succes', models.BooleanField(default=True)),
                ('message_erreur', models.TextField(blank=True)),
                ('boitier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques_sync', to='boitiers.boitier')),
            ],
            options={
                'ordering': ['-date_synchronisation'],
                'indexes': [models.Index(fields=['boitier', 'date_synchronisation'], name='boitiers_hi_boitier_367009_idx')],
            },
        ),
    ]
