# Generated by Django 6.0.6 on 2026-08-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boitiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boitier',
            name='api_key_hash_ancien',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='boitier',
            name='api_key_hash_ancien_expire_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
