# Generated by Django 6.0.6 on 2026-09-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boitiers', '0002_boitier_api_key_hash_ancien_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boitier',
            name='region',
            field=models.CharField(blank=True, choices=[('dakar', 'Dakar'), ('diourbel', 'Diourbel'), ('fatick', 'Fatick'), ('kaffrine', 'Kaffrine'), ('kaolack', 'Kaolack'), ('kedougou', 'Kédougou'), ('kolda', 'Kolda'), ('louga', 'Louga'), ('matam', 'Matam'), ('saint_louis', 'Saint-Louis'), ('sedhiou', 'Sédhiou'), ('tambacounda', 'Tambacounda'), ('thies', 'Thiès'), ('ziguinchor', 'Ziguinchor')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='boitier',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Arrêt volontaire'), ('maintenance', 'Maintenance')], default='actif', max_length=15),
        ),
    ]
