# Generated by Django 6.0.6 on 2026-10-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boitiers', '0003_boitier_region_alter_boitier_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='boitier',
            name='dernier_hdop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boitier',
            name='dernier_nombre_satellites',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boitier',
            name='derniere_vitesse_gps',
            field=models.FloatField(blank=True, help_text='km/h', null=True),
        ),
    ]
