# Generated by Django 6.0.6 on 2026-10-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boitiers', '0004_donnees_gps'),
    ]

    operations = [
        migrations.AddField(
            model_name='boitier',
            name='derniere_position_horodatage',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
