# Generated by Django 6.0.6 on 2026-10-10 16:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boitiers', '0005_position_horodatage_gps'),
        ('conducteurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueBoitier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evenement', models.CharField(choices=[('enregistre', 'Enregistré'), ('affecte', 'Affecté'), ('desaffecte', 'Désaffecté')], max_length=15)),
                ('role_acteur', models.CharField(blank=True, max_length=15)),
                ('commentaire', models.TextField(blank=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('acteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_boitiers', to=settings.AUTH_USER_MODEL)),
                ('boitier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='boitiers.boitier')),
                ('conducteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_boitiers', to='conducteurs.conducteur')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
