# Generated by Django 6.0.6 on 2026-07-05 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boitiers', '0001_initial'),
        ('incidents', '0001_initial'),
        ('zones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('incident_critique', 'Incident critique'), ('nouvelle_zone', 'Nouvelle zone'), ('zone_a_valider', 'Zone à valider'), ('sync_echouee', 'Synchronisation échouée'), ('feedback_anaser', 'Feedback ANASER')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('boitier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='boitiers.boitier')),
                ('destinataire', models.ForeignKey(blank=True, help_text='Null = notification diffusée à tous les administrateurs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='incidents.incident')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='zones.zone')),
            ],
            options={
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['destinataire', 'lue'], name='notificatio_destina_ecba0e_idx')],
            },
        ),
    ]
