# Generated by Django 6.0.6 on 2026-10-08 01:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationadmin',
            name='lue_par',
            field=models.ManyToManyField(blank=True, related_name='notifications_lues', to=settings.AUTH_USER_MODEL),
        ),
    ]
