# Generated by Django 6.0.6 on 2026-10-08 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_lue_par'),
        ('signalements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationadmin',
            name='signalement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='signalements.signalement'),
        ),
        migrations.AlterField(
            model_name='notificationadmin',
            name='type_notification',
            field=models.CharField(choices=[('incident_critique', 'Incident critique'), ('nouvelle_zone', 'Nouvelle zone'), ('zone_a_valider', 'Zone à valider'), ('sync_echouee', 'Synchronisation échouée'), ('feedback_anaser', 'Feedback ANASER'), ('nouveau_signalement', 'Nouveau signalement')], max_length=25),
        ),
    ]
