# Generated by Django 6.0.6 on 2026-10-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_signalement'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationadmin',
            name='audience',
            field=models.CharField(choices=[('personnel', 'Administrateurs et super administrateur'), ('anaser', 'ANASER')], default='personnel', max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationadmin',
            name='type_notification',
            field=models.CharField(choices=[('incident_critique', 'Incident critique'), ('nouvelle_zone', 'Nouvelle zone'), ('zone_a_valider', 'Zone à valider'), ('sync_echouee', 'Synchronisation échouée'), ('feedback_anaser', 'Feedback ANASER'), ('nouveau_signalement', 'Nouveau signalement'), ('zone_soumise_anaser', "Zone soumise à l'ANASER"), ('decision_anaser', "Décision de l'ANASER")], max_length=25),
        ),
    ]
