# Generated by Django 6.0.6 on 2026-10-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_audience_anaser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationadmin',
            name='type_notification',
            field=models.CharField(choices=[('incident_critique', 'Incident critique'), ('nouvelle_zone', 'Nouvelle zone'), ('zone_a_valider', 'Zone à valider'), ('sync_echouee', 'Synchronisation échouée'), ('feedback_anaser', 'Feedback ANASER'), ('nouveau_signalement', 'Nouveau signalement'), ('zone_soumise_anaser', "Zone soumise à l'ANASER"), ('decision_anaser', "Décision de l'ANASER"), ('nouvelle_demande', 'Nouvelle demande')], max_length=25),
        ),
    ]
