# Generated by Django 6.0.6 on 2026-09-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='region',
            field=models.CharField(blank=True, choices=[('dakar', 'Dakar'), ('diourbel', 'Diourbel'), ('fatick', 'Fatick'), ('kaffrine', 'Kaffrine'), ('kaolack', 'Kaolack'), ('kedougou', 'Kédougou'), ('kolda', 'Kolda'), ('louga', 'Louga'), ('matam', 'Matam'), ('saint_louis', 'Saint-Louis'), ('sedhiou', 'Sédhiou'), ('tambacounda', 'Tambacounda'), ('thies', 'Thiès'), ('ziguinchor', 'Ziguinchor')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='administrateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur régional'), ('super_admin', 'Super administrateur'), ('anaser', 'ANASER')], default='admin', max_length=15),
        ),
    ]
