# Generated by Django 6.0.6 on 2026-10-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_administrateur_region_alter_administrateur_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
