# Generated by Django 6.0.6 on 2026-07-05 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(blank=True, max_length=150)),
                ('latitude_centre', models.FloatField()),
                ('longitude_centre', models.FloatField()),
                ('rayon_metres', models.FloatField()),
                ('nombre_incidents', models.PositiveIntegerField(default=0)),
                ('score_danger', models.FloatField(default=0)),
                ('niveau_danger', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('eleve', 'Élevé'), ('critique', 'Critique')], default='faible', max_length=10)),
                ('statut_validation', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=10)),
                ('validee_le', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['statut_validation'], name='zones_zone_statut__c52efd_idx'), models.Index(fields=['actif'], name='zones_zone_actif_8313f0_idx')],
            },
        ),
    ]
