# Generated by Django 6.0.6 on 2026-08-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0002_niveau_danger_3_etats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='latitude_centre',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='longitude_centre',
            field=models.FloatField(db_index=True),
        ),
    ]
