# Generated by Django 6.0.6 on 2026-09-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0003_alter_zone_latitude_centre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='region',
            field=models.CharField(blank=True, choices=[('dakar', 'Dakar'), ('diourbel', 'Diourbel'), ('fatick', 'Fatick'), ('kaffrine', 'Kaffrine'), ('kaolack', 'Kaolack'), ('kedougou', 'Kédougou'), ('kolda', 'Kolda'), ('louga', 'Louga'), ('matam', 'Matam'), ('saint_louis', 'Saint-Louis'), ('sedhiou', 'Sédhiou'), ('tambacounda', 'Tambacounda'), ('thies', 'Thiès'), ('ziguinchor', 'Ziguinchor')], max_length=20, null=True),
        ),
    ]
