# Generated by Django 6.0.6 on 2026-10-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0005_workflow_validation_deux_etapes'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='nombre_signalements',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
