# Generated by Django 6.0.6 on 2026-10-08 21:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boitiers', '0005_position_horodatage_gps'),
        ('conducteurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('type_danger', models.CharField(choices=[('nid_de_poule', 'Nid-de-poule'), ('chaussee_degradee', 'Chaussée dégradée'), ('signalisation_absente', 'Signalisation absente'), ('chaussee_inondee', 'Chaussée inondée'), ('obstacle', 'Obstacle'), ('autre', 'Autre')], max_length=25)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('precision_metres', models.FloatField(blank=True, null=True)),
                ('region', models.CharField(choices=[('dakar', 'Dakar'), ('diourbel', 'Diourbel'), ('fatick', 'Fatick'), ('kaffrine', 'Kaffrine'), ('kaolack', 'Kaolack'), ('kedougou', 'Kédougou'), ('kolda', 'Kolda'), ('louga', 'Louga'), ('matam', 'Matam'), ('saint_louis', 'Saint-Louis'), ('sedhiou', 'Sédhiou'), ('tambacounda', 'Tambacounda'), ('thies', 'Thiès'), ('ziguinchor', 'Ziguinchor')], max_length=20)),
                ('localite', models.CharField(blank=True, max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='signalements/%Y/%m/')),
                ('statut', models.CharField(choices=[('a_verifier', 'À vérifier'), ('en_verification', 'En vérification'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='a_verifier', max_length=20)),
                ('boitier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to='boitiers.boitier')),
                ('conducteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to='conducteurs.conducteur')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStatutSignalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_precedent', models.CharField(choices=[('a_verifier', 'À vérifier'), ('en_verification', 'En vérification'), ('valide', 'Validé'), ('rejete', 'Rejeté')], max_length=20)),
                ('statut_nouveau', models.CharField(choices=[('a_verifier', 'À vérifier'), ('en_verification', 'En vérification'), ('valide', 'Validé'), ('rejete', 'Rejeté')], max_length=20)),
                ('role_acteur', models.CharField(max_length=15)),
                ('commentaire', models.TextField(blank=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('acteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_signalements', to=settings.AUTH_USER_MODEL)),
                ('signalement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_statuts', to='signalements.signalement')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='signalement',
            index=models.Index(fields=['region', 'statut'], name='signalement_region_5579e0_idx'),
        ),
        migrations.AddIndex(
            model_name='signalement',
            index=models.Index(fields=['latitude', 'longitude'], name='signalement_latitud_3ed5c3_idx'),
        ),
    ]
