# Generated by Django 6.0.6 on 2026-10-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquestatutsignalement',
            name='statut_nouveau',
            field=models.CharField(choices=[('a_verifier', 'À vérifier'), ('en_verification', 'En vérification'), ('valide', 'Validé techniquement'), ('rejete', 'Rejeté')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historiquestatutsignalement',
            name='statut_precedent',
            field=models.CharField(choices=[('a_verifier', 'À vérifier'), ('en_verification', 'En vérification'), ('valide', 'Validé techniquement'), ('rejete', 'Rejeté')], max_length=20),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='statut',
            field=models.CharField(choices=[('a_verifier', 'À vérifier'), ('en_verification', 'En vérification'), ('valide', 'Validé techniquement'), ('rejete', 'Rejeté')], default='a_verifier', max_length=20),
        ),
    ]
