# Generated by Django 6.0.6 on 2026-09-23 17:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boitiers', '0003_boitier_region_alter_boitier_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('adresse', models.CharField(blank=True, max_length=200)),
                ('pref_alertes_critiques', models.BooleanField(default=True)),
                ('pref_alertes_vigilance', models.BooleanField(default=True)),
                ('pref_annonce_vocale', models.BooleanField(default=False)),
                ('pref_sensibilite_nuit', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('boitier', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducteur', to='boitiers.boitier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
