# Generated by Django 6.0.6 on 2026-10-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conducteurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conducteur',
            name='contact_urgence_nom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='conducteur',
            name='contact_urgence_telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
