export const PATHS = {
  home: '/',
  carte: '/carte',
  aPropos: '/a-propos',
  actualites: '/actualites',
  /** Vue article — fiche technique « Page Actualités » §1 : même route logique, deux vues. */
  article: (id: string) => `/actualites/${id}`,
  articlePattern: '/actualites/:id',
  contact: '/contact',
  connexion: '/connexion',
  inscription: '/inscription',

  client: {
    root: '/client',
    carte: '/client/carte',
    alertes: '/client/alertes',
    trajets: '/client/trajets',
    signalements: '/client/signalements',
    profil: '/client/profil',
  },
  admin: {
    root: '/admin',
    monitoring: '/admin/monitoring',
    carte: '/admin/carte',
    incidents: '/admin/incidents',
    signalements: '/admin/signalements',
    zones: '/admin/zones',
    alertes: '/admin/alertes',
    boitiers: '/admin/boitiers',
    historique: '/admin/historique',
  },
  anaser: {
    root: '/anaser',
    incidents: '/anaser/incidents',
    zones: '/anaser/zones',
    statistiques: '/anaser/statistiques',
    retours: '/anaser/retours',
    profil: '/anaser/profil',
  },
  superAdmin: {
    root: '/super-admin',
    utilisateurs: '/super-admin/utilisateurs',
    boitiers: '/super-admin/boitiers',
    monitoring: '/super-admin/monitoring',
    incidents: '/super-admin/incidents',
    signalements: '/super-admin/signalements',
    zones: '/super-admin/zones',
    statistiques: '/super-admin/statistiques',
    notifications: '/super-admin/notifications',
    rapports: '/super-admin/rapports',
    configuration: '/super-admin/configuration',
    historique: '/super-admin/historique',
  },
} as const
