# Generated by Django 6.0.6 on 2026-07-05 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boitiers', '0001_initial'),
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('horodatage', models.DateTimeField()),
                ('recu_le', models.DateTimeField(auto_now_add=True)),
                ('type_incident', models.CharField(choices=[('choc_violent', 'Choc violent'), ('freinage_brusque', 'Freinage brusque'), ('collision', 'Collision'), ('chute', 'Chute'), ('autre', 'Autre')], max_length=20)),
                ('niveau_gravite', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('critique', 'Critique')], default='faible', max_length=10)),
                ('vitesse_radar', models.FloatField(blank=True, null=True)),
                ('acceleration_x', models.FloatField(blank=True, null=True)),
                ('acceleration_y', models.FloatField(blank=True, null=True)),
                ('acceleration_z', models.FloatField(blank=True, null=True)),
                ('gyro_x', models.FloatField(blank=True, null=True)),
                ('gyro_y', models.FloatField(blank=True, null=True)),
                ('gyro_z', models.FloatField(blank=True, null=True)),
                ('distance_hcsr04', models.FloatField(blank=True, null=True)),
                ('synced', models.BooleanField(default=True)),
                ('boitier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='boitiers.boitier')),
                ('historique_sync', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='boitiers.historiquesync')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='zones.zone')),
            ],
            options={
                'ordering': ['-horodatage'],
                'indexes': [models.Index(fields=['boitier', 'horodatage'], name='incidents_i_boitier_5ab819_idx'), models.Index(fields=['type_incident'], name='incidents_i_type_in_7911f2_idx'), models.Index(fields=['synced'], name='incidents_i_synced_41dd68_idx')],
            },
        ),
    ]
