# Generated by Django 6.0.6 on 2026-10-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boitiers', '0004_donnees_gps'),
        ('incidents', '0001_initial'),
        ('zones', '0005_workflow_validation_deux_etapes'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='hdop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='nombre_satellites',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='position_fiable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='vitesse_gps',
            field=models.FloatField(blank=True, help_text='km/h', null=True),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['position_fiable'], name='incidents_i_positio_a404ae_idx'),
        ),
    ]
