# Generated by Django 6.0.6 on 2026-10-10 17:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boitiers', '0006_historique_boitier'),
        ('incidents', '0002_donnees_gps'),
        ('zones', '0006_poids_signalements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_precedent', models.CharField(blank=True, choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('valide', 'Validé'), ('cloture', 'Clôturé'), ('rejete', 'Rejeté (faux positif)')], max_length=15)),
                ('statut_nouveau', models.CharField(blank=True, choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('valide', 'Validé'), ('cloture', 'Clôturé'), ('rejete', 'Rejeté (faux positif)')], max_length=15)),
                ('texte', models.TextField(blank=True)),
                ('role_acteur', models.CharField(max_length=15)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='statut',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('valide', 'Validé'), ('cloture', 'Clôturé'), ('rejete', 'Rejeté (faux positif)')], default='nouveau', max_length=15),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['statut'], name='incidents_i_statut_1c2beb_idx'),
        ),
        migrations.AddField(
            model_name='observationincident',
            name='acteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observationincident',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='incidents.incident'),
        ),
    ]
