# Generated by Django 6.0.6 on 2026-10-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_statut_traitement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='statut',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('valide', 'Validé techniquement'), ('cloture', 'Clôturé'), ('rejete', 'Rejeté (faux positif)')], default='nouveau', max_length=15),
        ),
        migrations.AlterField(
            model_name='observationincident',
            name='statut_nouveau',
            field=models.CharField(blank=True, choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('valide', 'Validé techniquement'), ('cloture', 'Clôturé'), ('rejete', 'Rejeté (faux positif)')], max_length=15),
        ),
        migrations.AlterField(
            model_name='observationincident',
            name='statut_precedent',
            field=models.CharField(blank=True, choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('valide', 'Validé techniquement'), ('cloture', 'Clôturé'), ('rejete', 'Rejeté (faux positif)')], max_length=15),
        ),
    ]
