# Generated by Django 6.0.6 on 2026-07-05 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatistiquesQuotidiennes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_incident', models.CharField(blank=True, choices=[('choc_violent', 'Choc violent'), ('freinage_brusque', 'Freinage brusque'), ('collision', 'Collision'), ('chute', 'Chute'), ('autre', 'Autre')], help_text="Null = tous types d'incidents confondus", max_length=20, null=True)),
                ('nombre_incidents', models.PositiveIntegerField(default=0)),
                ('nombre_incidents_critiques', models.PositiveIntegerField(default=0)),
                ('nombre_zones_actives', models.PositiveIntegerField(default=0)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(blank=True, help_text='Null = agrégat global (toutes zones confondues)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistiques_quotidiennes', to='zones.zone')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('date', 'zone', 'type_incident'), name='statistique_jour_zone_type_unique')],
            },
        ),
    ]
