# Generated by Django 6.0.6 on 2026-10-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistiques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistiquesquotidiennes',
            name='nombre_signalements',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
