# Generated by Django 6.0.6 on 2026-07-05 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alertes', '0001_initial'),
        ('boitiers', '0001_initial'),
        ('incidents', '0001_initial'),
        ('zones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='incident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alerte', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='alerte',
            name='traitee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_traitees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerteproximite',
            name='boitier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_proximite', to='boitiers.boitier'),
        ),
        migrations.AddField(
            model_name='alerteproximite',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_proximite', to='zones.zone'),
        ),
        migrations.AddIndex(
            model_name='alerteproximite',
            index=models.Index(fields=['boitier', 'zone', 'date_creation'], name='alertes_ale_boitier_c39344_idx'),
        ),
    ]
