# Generated by Django 6.0.6 on 2026-07-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerteproximite',
            name='notifiee',
        ),
        migrations.AddField(
            model_name='alerteproximite',
            name='canal_audio_declenche',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alerteproximite',
            name='canal_buzzer_declenche',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alerteproximite',
            name='canal_led',
            field=models.CharField(choices=[('vert', 'Vert'), ('jaune', 'Jaune'), ('rouge', 'Rouge')], default='vert', max_length=10),
        ),
    ]
