# Generated by Django 6.0.6 on 2026-10-10 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertes', '0003_remove_alerteproximite_notifiee_and_more'),
        ('conducteurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerteproximite',
            name='conducteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_proximite', to='conducteurs.conducteur'),
        ),
    ]
