# Generated by Django 6.0.6 on 2026-10-10 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def convertir_alertes_existantes(apps, schema_editor):
    """Alertes créées avant les sources : toutes issues d'un incident critique (source
    véhicule). « vue » devient « en_cours » ; boîtier et conducteur repris de l'incident."""
    Alerte = apps.get_model('alertes', 'Alerte')
    Conducteur = apps.get_model('conducteurs', 'Conducteur')
    for alerte in Alerte.objects.select_related('incident'):
        if alerte.statut == 'vue':
            alerte.statut = 'en_cours'
        if alerte.incident_id and not alerte.boitier_id:
            alerte.boitier_id = alerte.incident.boitier_id
            alerte.conducteur = Conducteur.objects.filter(boitier_id=alerte.boitier_id).first()
        alerte.save(update_fields=['statut', 'boitier', 'conducteur'])


class Migration(migrations.Migration):

    dependencies = [
        ('alertes', '0004_alerte_conducteur'),
        ('boitiers', '0006_historique_boitier'),
        ('conducteurs', '0001_initial'),
        ('incidents', '0004_libelle_validation_technique'),
        ('zones', '0006_poids_signalements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='boitier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='boitiers.boitier'),
        ),
        migrations.AddField(
            model_name='alerte',
            name='conducteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='conducteurs.conducteur'),
        ),
        migrations.AddField(
            model_name='alerte',
            name='motif',
            field=models.CharField(choices=[('incident', 'Incident détecté'), ('hors_ligne', 'Boîtier hors ligne')], default='incident', max_length=15),
        ),
        migrations.AddField(
            model_name='alerte',
            name='niveau',
            field=models.CharField(choices=[('vigilance', 'Vigilance'), ('critique', 'Critique')], default='critique', max_length=10),
        ),
        migrations.AddField(
            model_name='alerte',
            name='prise_en_charge_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alerte',
            name='prise_en_charge_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_prises_en_charge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerte',
            name='source',
            field=models.CharField(choices=[('zone', 'Zone à risque'), ('vehicule', 'Véhicule'), ('boitier', 'Boîtier')], default='vehicule', max_length=10),
        ),
        migrations.AddField(
            model_name='alerte',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='zones.zone'),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='incident',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerte', to='incidents.incident'),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='statut',
            field=models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_cours', 'En cours'), ('traitee', 'Traitée')], default='nouvelle', max_length=10),
        ),
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['statut', 'source'], name='alertes_ale_statut_4258c5_idx'),
        ),
        migrations.RunPython(convertir_alertes_existantes, migrations.RunPython.noop),
    ]
