# Generated by Django 6.0.6 on 2026-10-10 20:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boitiers', '0006_historique_boitier'),
        ('conducteurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('region', models.CharField(choices=[('dakar', 'Dakar'), ('diourbel', 'Diourbel'), ('fatick', 'Fatick'), ('kaffrine', 'Kaffrine'), ('kaolack', 'Kaolack'), ('kedougou', 'Kédougou'), ('kolda', 'Kolda'), ('louga', 'Louga'), ('matam', 'Matam'), ('saint_louis', 'Saint-Louis'), ('sedhiou', 'Sédhiou'), ('tambacounda', 'Tambacounda'), ('thies', 'Thiès'), ('ziguinchor', 'Ziguinchor')], max_length=20)),
                ('commune', models.CharField(max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=200)),
                ('type_vehicule', models.CharField(choices=[('voiture', 'Voiture particulière'), ('taxi', 'Taxi'), ('bus', 'Bus / car'), ('camion', 'Camion'), ('moto', 'Moto'), ('autre', 'Autre')], max_length=10)),
                ('immatriculation', models.CharField(blank=True, max_length=30)),
                ('nombre_vehicules', models.PositiveSmallIntegerField(default=1)),
                ('disponibilites', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('consentement_donnees', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('contactee', 'Contactée'), ('rdv_planifie', 'Rendez-vous planifié'), ('installee', 'Installée'), ('annulee', 'Annulée')], default='nouvelle', max_length=15)),
                ('rdv_date', models.DateTimeField(blank=True, null=True)),
                ('rdv_lieu', models.CharField(blank=True, max_length=200)),
                ('numero_cni', models.CharField(blank=True, max_length=30)),
                ('boitier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_installation', to='boitiers.boitier')),
                ('conducteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_installation', to='conducteurs.conducteur')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_precedent', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('contactee', 'Contactée'), ('rdv_planifie', 'Rendez-vous planifié'), ('installee', 'Installée'), ('annulee', 'Annulée')], max_length=15)),
                ('statut_nouveau', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('contactee', 'Contactée'), ('rdv_planifie', 'Rendez-vous planifié'), ('installee', 'Installée'), ('annulee', 'Annulée')], max_length=15)),
                ('role_acteur', models.CharField(max_length=15)),
                ('commentaire', models.TextField(blank=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('acteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_demandes', to=settings.AUTH_USER_MODEL)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='demandes.demandeinstallation')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('sujet', models.CharField(choices=[('question', 'Question générale'), ('signalement', 'Signalement'), ('suggestion', 'Suggestion'), ('partenariat', 'Partenariat'), ('support', 'Support technique'), ('autre', 'Autre')], max_length=15)),
                ('message', models.TextField()),
                ('traite', models.BooleanField(default=False)),
                ('traite_le', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_traites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddIndex(
            model_name='demandeinstallation',
            index=models.Index(fields=['region', 'statut'], name='demandes_de_region_a36629_idx'),
        ),
    ]
