# Generated by Django 6.0.6 on 2026-07-05 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seuil_acceleration_critique', models.FloatField(default=25.0, help_text='m/s², au-delà = incident critique')),
                ('seuil_vitesse_choc', models.FloatField(default=60.0, help_text='km/h, au-delà = incident critique')),
                ('rayon_clustering_metres', models.FloatField(default=300.0)),
                ('min_incidents_pour_zone', models.PositiveIntegerField(default=3)),
                ('rayon_alerte_proximite_metres', models.FloatField(default=1000.0)),
                ('intervalle_sync_secondes', models.PositiveIntegerField(default=60, help_text='Informatif pour le firmware')),
                ('cooldown_alerte_proximite_minutes', models.PositiveIntegerField(default=15)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
