# Generated by Django 6.0.6 on 2026-08-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_configuration_initiale'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationsysteme',
            name='duree_grace_regeneration_cle_heures',
            field=models.PositiveIntegerField(default=24, help_text="Durée pendant laquelle l'ancienne clé API d'un boîtier reste valide après régénération, le temps de reconfigurer le dispositif sur le terrain."),
        ),
    ]
