# Generated by Django 6.0.6 on 2026-10-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_configurationsysteme_duree_grace_regeneration_cle_heures'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationsysteme',
            name='gps_hdop_max',
            field=models.FloatField(default=5.0, help_text='HDOP maximal pour une position GPS fiable (plus petit = plus précis)'),
        ),
        migrations.AddField(
            model_name='configurationsysteme',
            name='gps_satellites_min',
            field=models.PositiveSmallIntegerField(default=4, help_text='Nombre minimal de satellites pour une position GPS fiable'),
        ),
    ]
