# Generated by Django 6.0.6 on 2026-10-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_donnees_gps'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationsysteme',
            name='poids_signalement_valide',
            field=models.FloatField(default=0.5, help_text="Points ajoutés au score d'une zone par signalement validé dans son rayon"),
        ),
    ]
