# Generated by Django 6.0.6 on 2026-10-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_poids_signalements'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationsysteme',
            name='delai_hors_ligne_minutes',
            field=models.PositiveIntegerField(default=30, help_text="Minutes sans données avant qu'un boîtier actif soit signalé hors ligne"),
        ),
    ]
